'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowRight, Check, ChevronDown, FileImage, FileText, Files, Gauge, GripVertical, Layers, Menu, ShieldCheck, Sparkles, Upload, X, Zap } from 'lucide-react'

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:4000'

export type ToolKey = 'pdf-to-word' | 'word-to-pdf' | 'jpg-to-pdf' | 'pdf-to-jpg' | 'merge-pdf' | 'split-pdf' | 'compress-pdf'
type Category = 'Convert' | 'Organize' | 'Optimize'
export const tools: { key: ToolKey; title: string; description: string; category: Category; icon: typeof FileText; accent: string }[] = [
  { key: 'pdf-to-word', title: 'PDF to Word', description: 'Convert PDF files into editable Word documents.', category: 'Convert', icon: FileText, accent: '#19b7c9' },
  { key: 'word-to-pdf', title: 'Word to PDF', description: 'Turn Word documents into polished PDF files.', category: 'Convert', icon: FileText, accent: '#3568e8' },
  { key: 'jpg-to-pdf', title: 'JPG to PDF', description: 'Convert images into a single professional PDF.', category: 'Convert', icon: FileImage, accent: '#6d5dfc' },
  { key: 'pdf-to-jpg', title: 'PDF to JPG', description: 'Convert PDF pages into high-quality JPG images.', category: 'Convert', icon: FileImage, accent: '#e6a642' },
  { key: 'merge-pdf', title: 'Merge PDF', description: 'Combine multiple PDF files into one document.', category: 'Organize', icon: Layers, accent: '#34c6a3' },
  { key: 'split-pdf', title: 'Split PDF', description: 'Extract pages or divide a PDF into separate files.', category: 'Organize', icon: Files, accent: '#d36b9b' },
  { key: 'compress-pdf', title: 'Compress PDF', description: 'Reduce PDF file size while keeping great quality.', category: 'Optimize', icon: Gauge, accent: '#ef765f' },
]

export function Navbar() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><div className="container nav-inner"><Link className="brand" href="/"><span className="brand-mark"><Sparkles size={16} /></span>PDFmesh</Link><nav className={open ? 'nav-links nav-open' : 'nav-links'}><a href="/#tools" onClick={() => setOpen(false)}>PDF Tools</a><a href="/#features" onClick={() => setOpen(false)}>Features</a><a href="/#pricing" onClick={() => setOpen(false)}>Pricing</a><a href="/#faq" onClick={() => setOpen(false)}>FAQ</a><div className="nav-actions"><button className="button button-ghost">Sign In</button><button className="button button-primary">Get Started</button></div></nav><button aria-label="Toggle menu" className="menu-button" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header>
}

export function Footer() { return <footer className="footer"><div className="container footer-grid"><div><Link className="brand" href="/"><span className="brand-mark"><Sparkles size={16} /></span>PDFmesh</Link><p className="footer-note">The simpler way to work with everyday documents.</p></div>{[['Product','Features','Pricing','Security'],['Tools','PDF to Word','Merge PDF','Compress PDF'],['Company','About us','Contact','Careers'],['Legal','Privacy','Terms','Cookies']].map(([title,...links]) => <div key={title}><h4>{title}</h4>{links.map(item => <a href="#" key={item}>{item}</a>)}</div>)}</div><div className="container footer-bottom"><span>© 2026 PDFmesh. All rights reserved.</span><span>Made for better workflows.</span></div></footer> }

function ToolSymbol({ toolKey, accent, size = 'card' }: { toolKey: ToolKey; accent: string; size?: 'card' | 'page' }) { const isMerge = toolKey === 'merge-pdf'; const isSplit = toolKey === 'split-pdf'; const isCompress = toolKey === 'compress-pdf'; const source = toolKey.includes('word') ? 'W' : toolKey.includes('jpg') ? 'JPG' : 'PDF'; const target = toolKey === 'pdf-to-word' ? 'W' : toolKey === 'word-to-pdf' ? 'PDF' : toolKey === 'pdf-to-jpg' || toolKey === 'jpg-to-pdf' ? 'JPG' : 'PDF'; const marker = isMerge ? 'merge' : isSplit ? 'split' : isCompress ? 'compress' : 'convert'; return <svg className={`tool-symbol tool-symbol-${size} tool-symbol-${marker}`} viewBox="0 0 52 52" style={{ '--symbol-accent': accent } as React.CSSProperties} aria-hidden="true"><defs><marker id={`arrow-${toolKey}-${size}`} markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0 0 5 2.5 0 5Z" fill="currentColor" /></marker></defs>{isMerge ? <><rect x="5" y="7" width="20" height="20" rx="4" fill="currentColor" opacity=".38"/><rect x="27" y="25" width="20" height="20" rx="4" fill="currentColor" opacity=".92"/><path d="M17 21 30 34M35 21 22 34" stroke="currentColor" strokeWidth="3" strokeLinecap="round" markerEnd={`url(#arrow-${toolKey}-${size})`}/></> : isSplit ? <><rect x="16" y="16" width="20" height="20" rx="4" fill="currentColor" opacity=".92"/><path d="M25 25 11 11M27 27 41 41" stroke="currentColor" strokeWidth="3" strokeLinecap="round" markerEnd={`url(#arrow-${toolKey}-${size})`}/></> : isCompress ? <><rect x="16" y="16" width="20" height="20" rx="4" fill="currentColor" opacity=".9"/><path d="M7 7 16 16M45 7 36 16M7 45 16 36M45 45 36 36" stroke="currentColor" strokeWidth="3" strokeLinecap="round" markerEnd={`url(#arrow-${toolKey}-${size})`}/></> : <><rect x="4" y="7" width="21" height="21" rx="4" fill="currentColor" opacity=".32"/><text x="14.5" y="20" textAnchor="middle" fontSize={source.length > 2 ? 5.5 : 10} fontWeight="800" fill="currentColor">{source}</text><rect x="27" y="24" width="21" height="21" rx="4" fill="currentColor" opacity=".92"/><text x="37.5" y="38" textAnchor="middle" fontSize={target.length > 2 ? 5.5 : 10} fontWeight="800" fill="white">{target}</text><path d="M20 28 31 37" stroke="currentColor" strokeWidth="3" strokeLinecap="round" markerEnd={`url(#arrow-${toolKey}-${size})`}/></>}</svg> }
function ToolCard({ tool }: { tool: typeof tools[number] }) { return <Link href={`/${tool.key}`} className="tool-card" style={{ '--card-accent': tool.accent } as React.CSSProperties}><div className="tool-icon"><ToolSymbol toolKey={tool.key} accent={tool.accent} /></div><div className="tool-card-copy"><h3>{tool.title}</h3><p>{tool.description}</p></div><span className="tool-link">Open tool <ArrowRight size={15} /></span></Link> }
function ToolGrid() { const [category, setCategory] = useState<'All' | Category>('All'); const cats = ['All','Convert','Organize','Optimize'] as const; return <section id="tools" className="section tools-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Powerful, focused tools</span><h2>Everything in one place.</h2></div><p>Choose the tool that fits your workflow and get more done with less friction.</p></div><div className="tabs" role="tablist">{cats.map(cat => <button key={cat} className={category === cat ? 'tab active' : 'tab'} onClick={() => setCategory(cat)}>{cat}</button>)}</div><div className="tool-grid">{tools.filter(tool => category === 'All' || tool.category === category).map(tool => <ToolCard key={tool.key} tool={tool} />)}</div></div></section> }

export function HomePage() { return <><Navbar /><main><section className="hero"><div className="hero-glow" /><div className="container hero-content"><span className="eyebrow">A sharper standard for document work</span><h1>Move every document<br /><span>forward with confidence.</span></h1><p>Precision tools for converting, organizing, and optimizing the files that keep work moving.</p><div className="hero-actions"><a className="button button-primary button-large" href="#tools">Explore PDF Tools <ArrowRight size={17} /></a><a className="button button-secondary button-large" href="#how">How it works <ChevronDown size={16} /></a></div><div className="hero-proof"><div className="avatar-stack"><span>J</span><span>M</span><span>A</span><span>+</span></div><span>Trusted by teams who value their time</span></div></div></section><ToolGrid /><section id="features" className="section trust-section"><div className="container"><div className="center-heading"><span className="eyebrow">Built around your workflow</span><h2>Simple. Secure. Built for<br />everyday documents.</h2></div><div className="feature-grid">{[[ShieldCheck,'Private by design','Your files are yours. We keep your workflow focused and your documents protected.'],[Zap,'Fast processing','No unnecessary steps. Get from upload to finished document in a few clicks.'],[Sparkles,'Easy to use','A clear, thoughtful experience that feels natural from the very first file.']].map(([Icon,title,text]) => <div className="feature-card" key={title as string}><div className="feature-icon"><Icon size={22} /></div><h3>{title as string}</h3><p>{text as string}</p></div>)}</div></div></section><section id="how" className="section how-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">A better way to work</span><h2>Three steps. Zero guesswork.</h2></div></div><div className="steps">{[['01','Choose a tool','Start with the document task you need to complete.'],['02','Upload your file','Drag and drop your file or select it from your device.'],['03','Download the result','Your finished document is ready to use and share.']].map(([number,title,text]) => <div className="step" key={number}><span className="step-number">{number}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section><section id="pricing" className="cta-section"><div className="container cta-inner"><div><span className="eyebrow eyebrow-light">Make room for better work</span><h2>Ready to simplify your<br />PDF workflow?</h2></div><a className="button button-light button-large" href="#tools">Start using PDFmesh <ArrowRight size={17} /></a></div></section></main><Footer /></> }

const configs: Record<ToolKey,{title:string; description:string; accept:string; action:string; result:string; multiple?:boolean}> = { 'pdf-to-word':{title:'PDF to Word',description:'Convert your PDF files into editable Word documents.',accept:'PDF',action:'Convert to Word',result:'DOCX'},'word-to-pdf':{title:'Word to PDF',description:'Turn your Word documents into polished PDF files.',accept:'DOC or DOCX',action:'Convert to PDF',result:'PDF'},'jpg-to-pdf':{title:'JPG to PDF',description:'Convert images into a single professional PDF.',accept:'JPG or PNG',action:'Create PDF',result:'PDF',multiple:true},'pdf-to-jpg':{title:'PDF to JPG',description:'Convert PDF pages into high-quality JPG images.',accept:'PDF',action:'Convert to JPG',result:'JPG'},'merge-pdf':{title:'Merge PDF',description:'Combine multiple PDF files into one document.',accept:'PDF',action:'Merge PDFs',result:'PDF',multiple:true},'split-pdf':{title:'Split PDF',description:'Extract pages or divide a PDF into separate files.',accept:'PDF',action:'Split PDF',result:'PDF'},'compress-pdf':{title:'Compress PDF',description:'Reduce PDF file size while keeping great quality.',accept:'PDF',action:'Compress PDF',result:'PDF'} }

function FileList({ files, remove, reorder }: { files: File[]; remove:(i:number)=>void; reorder:(from:number,to:number)=>void }) { const [dragged,setDragged]=useState<number|null>(null); return <div className="file-list">{files.map((file,i) => <div className={dragged===i ? 'file-row is-dragging' : 'file-row'} draggable onDragStart={e => { setDragged(i); e.dataTransfer.effectAllowed='move'; e.dataTransfer.setData('text/plain',String(i)) }} onDragEnd={() => setDragged(null)} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); reorder(Number(e.dataTransfer.getData('text/plain')),i); setDragged(null) }} key={`${file.name}-${i}`}><GripVertical className="grip" size={17}/><div className="file-badge"><FileText size={18}/></div><div className="file-meta"><strong>{file.name}</strong><span>{(file.size/1024/1024).toFixed(2)} MB</span></div><button className="icon-button" aria-label={`Remove ${file.name}`} onClick={() => remove(i)}><X size={17}/></button></div>)}</div> }
function UploadZone({ select, multiple, accept }: {select:(files:File[])=>void; multiple?:boolean; accept:string}) { const [dragging,setDragging]=useState(false); return <label className={dragging ? 'upload-zone is-dragging' : 'upload-zone'} onDragOver={e => { e.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={e => { e.preventDefault(); setDragging(false); select(Array.from(e.dataTransfer.files)) }}><input type="file" accept={accept} multiple={multiple} onChange={e => select(Array.from(e.target.files || []))}/><div className="upload-icon"><Upload size={22}/></div><h3>{dragging ? 'Drop to add your files' : `Drag & drop your ${accept} here`}</h3><p>{dragging ? 'Release to continue' : 'or choose a file from your device'}</p><span className="button button-primary">Select {multiple ? 'files' : 'a file'}</span><small>Maximum file size: 50 MB</small></label> }
function StateMessage({ type, config, reset, errorMessage, downloadUrl, downloadName, onDownload }: {type:'processing'|'success'|'error'; config:typeof configs[ToolKey]; reset:()=>void; errorMessage?:string; downloadUrl?:string; downloadName?:string; onDownload?:(e?:{ preventDefault:()=>void })=>void}) { const [progress,setProgress]=useState(8); useEffect(() => { if (type !== 'processing') return; const timer=window.setInterval(() => setProgress(value => Math.min(value + 9, 92)), 420); return () => window.clearInterval(timer) }, [type]); if(type==='processing') return <div className="state-card" aria-live="polite"><div className="loader"><span /></div><h2>Processing your file...</h2><div className="progress"><span style={{ width: `${progress}%` }} /></div><strong>{progress}%</strong><p>Please wait while we prepare your document.</p></div>; if(type==='error') return <div className="state-card"><div className="state-icon error"><X size={25}/></div><h2>Something went wrong</h2><p>{errorMessage || 'Please try again or choose another file.'}</p><button className="button button-primary" onClick={reset}>Try again</button></div>; const fileName = downloadName || `document.${config.result.toLowerCase()}`; const downloadLabel = (fileName.split('.').pop() || config.result).toUpperCase(); return <div className="state-card"><div className="state-icon"><Check size={25}/></div><h2>Your file is ready!</h2><p>{fileName}</p><div className="state-actions">{downloadUrl ? <a className="button button-primary" href={downloadUrl} download={fileName} onClick={onDownload}>Download {downloadLabel}</a> : <button className="button button-primary">Download {config.result}</button>}<button className="button button-secondary" onClick={reset}>Convert another file</button></div></div> }
export function ToolPage({ toolKey }: {toolKey:ToolKey}) { const config=configs[toolKey]; const [files,setFiles]=useState<File[]>([]); const [state,setState]=useState<'idle'|'processing'|'success'|'error'>('idle'); const [downloadUrl,setDownloadUrl]=useState<string|null>(null); const [downloadBlob,setDownloadBlob]=useState<Blob|null>(null); const [downloadName,setDownloadName]=useState<string|undefined>(undefined); const [errorMessage,setErrorMessage]=useState<string|undefined>(undefined); const [compressLevel,setCompressLevel]=useState<'extreme'|'recommended'|'less'>('recommended'); const select=(newFiles:File[])=>{ if(!config.multiple){ setFiles(newFiles.slice(0,1)); return } setFiles(prev => { const merged=[...prev]; for(const f of newFiles){ if(!merged.some(e => e.name===f.name && e.size===f.size)) merged.push(f) } return merged }) }; const reset=()=>{ if(downloadUrl) URL.revokeObjectURL(downloadUrl); setDownloadUrl(null); setDownloadBlob(null); setDownloadName(undefined); setErrorMessage(undefined); setFiles([]); setState('idle') }; useEffect(() => () => { if(downloadUrl) URL.revokeObjectURL(downloadUrl) }, [downloadUrl]); const reorder=(from:number,to:number)=>{const next=[...files]; const [item]=next.splice(from,1); next.splice(to,0,item);setFiles(next)};
  /* Cross-platform download. Desktop keeps the standard anchor+download behavior. Mobile Safari/Chrome often ignore the download attribute on blob URLs, so we route through a programmatic anchor and fall back to opening the file on iOS. */
  const triggerDownload=(e?:{ preventDefault:()=>void })=>{ if(e) e.preventDefault(); const name=downloadName || `document.${config.result.toLowerCase()}`; const blob=downloadBlob; const href=downloadUrl; if(!href) return; const ua=typeof navigator!=='undefined' ? navigator.userAgent : ''; const isIOS=/iP(ad|hone|od)/.test(ua) || (/(Macintosh)/.test(ua) && typeof document!=='undefined' && 'ontouchend' in document); const a=document.createElement('a'); a.href=href; a.download=name; a.rel='noopener'; document.body.appendChild(a); a.click(); document.body.removeChild(a); if(isIOS && blob){ window.open(href,'_blank'); } };
  const convertPdfToWord=async()=>{ const file=files[0]; if(!file) return; setErrorMessage(undefined); setState('processing'); try { const formData=new FormData(); formData.append('file',file); const response=await fetch(`${API_BASE_URL}/api/pdf-to-docx`,{ method:'POST', body:formData }); if(!response.ok){ let message='The conversion failed. Please try again or choose another file.'; try { const data=await response.json(); if(data && typeof data.error==='string') message=data.error } catch {} setErrorMessage(message); setState('error'); return } const blob=await response.blob(); const url=URL.createObjectURL(blob); const baseName=file.name.replace(/\.[^.]+$/,'') || 'document'; setDownloadBlob(blob); setDownloadUrl(url); setDownloadName(`${baseName}.docx`); setState('success') } catch { setErrorMessage('Could not reach the conversion service. Please check your connection and try again.'); setState('error') } };
  // Free, faithful utility tools handled by the backend (field name: "files").
  // Each returns a downloadable blob (PDF or ZIP) with a sensible filename.
  const TOOL_ENDPOINTS: Partial<Record<ToolKey,{ path:string; outName:(f:File[])=>string }>> = {
    'merge-pdf': { path:'/api/merge-pdf', outName:()=>'merged.pdf' },
    'split-pdf': { path:'/api/split-pdf', outName:(f)=>`${(f[0]?.name||'document').replace(/\.[^.]+$/,'')}_pages.zip` },
    'pdf-to-jpg': { path:'/api/pdf-to-jpg', outName:(f)=>`${(f[0]?.name||'document').replace(/\.[^.]+$/,'')}_images.zip` },
    'jpg-to-pdf': { path:'/api/jpg-to-pdf', outName:()=>'images.pdf' },
    'compress-pdf': { path:'/api/compress-pdf', outName:(f)=>`${(f[0]?.name||'document').replace(/\.[^.]+$/,'')}_compressed.pdf` },
    'word-to-pdf': { path:'/api/word-to-pdf', outName:(f)=>`${(f[0]?.name||'document').replace(/\.[^.]+$/,'')}.pdf` },
  };
  const runToolOp=async()=>{ const spec=TOOL_ENDPOINTS[toolKey]; if(!spec || files.length===0) return; setErrorMessage(undefined); setState('processing'); try { const formData=new FormData(); for(const f of files) formData.append('files',f); if(toolKey==='compress-pdf') formData.append('level',compressLevel); const response=await fetch(`${API_BASE_URL}${spec.path}`,{ method:'POST', body:formData }); if(!response.ok){ let message='The operation failed. Please try again or choose another file.'; try { const data=await response.json(); if(data && typeof data.error==='string') message=data.error } catch {} setErrorMessage(message); setState('error'); return } const blob=await response.blob(); const url=URL.createObjectURL(blob); const name=spec.outName(files); setDownloadBlob(blob); setDownloadUrl(url); setDownloadName(name); setState('success') } catch { setErrorMessage('Could not reach the service. Please check your connection and try again.'); setState('error') } };
  const handleProcess=()=>{ if(toolKey==='pdf-to-word'){ void convertPdfToWord(); return } if(TOOL_ENDPOINTS[toolKey]){ void runToolOp(); return } setState('processing'); setTimeout(()=>setState('success'),1400) };
  return <><Navbar/><main className="tool-page"><div className="container tool-page-inner"><Link href="/" className="back-link">← All PDF tools</Link><div className="tool-header"><div className="tool-page-icon"><ToolSymbol toolKey={toolKey} accent={toolKey === 'pdf-to-word' ? '#3568e8' : toolKey.includes('jpg') ? '#d6bd1d' : toolKey === 'compress-pdf' ? '#83b95b' : '#ef765f'} size="page" /></div><span className="eyebrow">PDFmesh tool</span><h1>{config.title}</h1><p>{config.description}</p></div><div className="workspace">{state !== 'idle' ? <StateMessage type={state} config={config} reset={reset} errorMessage={errorMessage} downloadUrl={downloadUrl || undefined} downloadName={downloadName} onDownload={triggerDownload}/> : files.length===0 ? <UploadZone select={select} multiple={config.multiple} accept={config.accept}/> : <div className="uploaded-state"><div className="workspace-top"><div><span className="eyebrow">Ready to process</span><h2>Your {config.multiple ? 'files are' : 'file is'} ready.</h2></div><div className="workspace-top-actions">{config.multiple && <label className="button button-secondary add-more-button"><input type="file" accept={config.accept} multiple onChange={e => { select(Array.from(e.target.files || [])); e.currentTarget.value='' }} hidden/>Add more files</label>}<button className="button button-ghost" onClick={reset}>Clear all</button></div></div><FileList files={files} remove={i=>setFiles(files.filter((_,idx)=>idx!==i))} reorder={reorder}/>{toolKey==='compress-pdf' && <div className="option-grid"><button type="button" className={compressLevel==='extreme' ? 'option-card selected' : 'option-card'} onClick={()=>setCompressLevel('extreme')}><strong>Extreme</strong><span>Smallest file</span></button><button type="button" className={compressLevel==='recommended' ? 'option-card selected' : 'option-card'} onClick={()=>setCompressLevel('recommended')}><strong>Recommended</strong><span>Great balance</span></button><button type="button" className={compressLevel==='less' ? 'option-card selected' : 'option-card'} onClick={()=>setCompressLevel('less')}><strong>Less compression</strong><span>Best quality</span></button></div>}{toolKey==='pdf-to-jpg' && <div className="quality-row"><strong>Image quality</strong><button className="quality active">High</button><button className="quality">Medium</button><button className="quality">Low</button></div>}<button className="button button-primary button-large process-button" onClick={handleProcess}>{config.action} <ArrowRight size={17}/></button></div>}</div><p className="security-note"><ShieldCheck size={16}/> Files are processed securely and never shared.</p></div></main><Footer/></> }
