'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, FileImage, FileText, Files, Gauge, GripVertical, Layers, Menu, ShieldCheck, Sparkles, Upload, X, Zap } from 'lucide-react'

export type ToolKey = 'pdf-to-word' | 'word-to-pdf' | 'jpg-to-pdf' | 'pdf-to-jpg' | 'merge-pdf' | 'split-pdf' | 'compress-pdf'
type Category = 'Convert' | 'Organize' | 'Optimize'
export const tools: { key: ToolKey; title: string; description: string; category: Category; icon: typeof FileText }[] = [
  { key: 'pdf-to-word', title: 'PDF to Word', description: 'Convert PDF files into editable Word documents.', category: 'Convert', icon: FileText },
  { key: 'word-to-pdf', title: 'Word to PDF', description: 'Turn Word documents into polished PDF files.', category: 'Convert', icon: FileText },
  { key: 'jpg-to-pdf', title: 'JPG to PDF', description: 'Convert images into a single professional PDF.', category: 'Convert', icon: FileImage },
  { key: 'pdf-to-jpg', title: 'PDF to JPG', description: 'Convert PDF pages into high-quality JPG images.', category: 'Convert', icon: FileImage },
  { key: 'merge-pdf', title: 'Merge PDF', description: 'Combine multiple PDF files into one document.', category: 'Organize', icon: Layers },
  { key: 'split-pdf', title: 'Split PDF', description: 'Extract pages or divide a PDF into separate files.', category: 'Organize', icon: Files },
  { key: 'compress-pdf', title: 'Compress PDF', description: 'Reduce PDF file size while keeping great quality.', category: 'Optimize', icon: Gauge },
]

export function Navbar() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><div className="container nav-inner"><Link className="brand" href="/"><span className="brand-mark"><Sparkles size={16} /></span>DocFlow</Link><nav className={open ? 'nav-links nav-open' : 'nav-links'}><a href="/#tools" onClick={() => setOpen(false)}>PDF Tools</a><a href="/#features" onClick={() => setOpen(false)}>Features</a><a href="/#pricing" onClick={() => setOpen(false)}>Pricing</a><a href="/#faq" onClick={() => setOpen(false)}>FAQ</a><div className="nav-actions"><button className="button button-ghost">Sign In</button><button className="button button-primary">Get Started</button></div></nav><button aria-label="Toggle menu" className="menu-button" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div></header>
}

export function Footer() { return <footer className="footer"><div className="container footer-grid"><div><Link className="brand" href="/"><span className="brand-mark"><Sparkles size={16} /></span>DocFlow</Link><p className="footer-note">The simpler way to work with everyday documents.</p></div>{[['Product','Features','Pricing','Security'],['Tools','PDF to Word','Merge PDF','Compress PDF'],['Company','About us','Contact','Careers'],['Legal','Privacy','Terms','Cookies']].map(([title,...links]) => <div key={title}><h4>{title}</h4>{links.map(item => <a href="#" key={item}>{item}</a>)}</div>)}</div><div className="container footer-bottom"><span>© 2026 DocFlow. All rights reserved.</span><span>Made for better workflows.</span></div></footer> }

function ToolCard({ tool }: { tool: typeof tools[number] }) { const Icon = tool.icon; return <Link href={`/${tool.key}`} className="tool-card"><div className="tool-icon"><Icon size={21} /></div><div className="tool-card-copy"><h3>{tool.title}</h3><p>{tool.description}</p></div><span className="tool-link">Open tool <ArrowRight size={15} /></span></Link> }
function ToolGrid() { const [category, setCategory] = useState<'All' | Category>('All'); const cats = ['All','Convert','Organize','Optimize'] as const; return <section id="tools" className="section tools-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Powerful, focused tools</span><h2>Everything in one place.</h2></div><p>Choose the tool that fits your workflow and get more done with less friction.</p></div><div className="tabs" role="tablist">{cats.map(cat => <button key={cat} className={category === cat ? 'tab active' : 'tab'} onClick={() => setCategory(cat)}>{cat}</button>)}</div><div className="tool-grid">{tools.filter(tool => category === 'All' || tool.category === category).map(tool => <ToolCard key={tool.key} tool={tool} />)}</div></div></section> }

export function HomePage() { return <><Navbar /><main><section className="hero"><div className="hero-glow" /><div className="container hero-content"><span className="eyebrow">Your documents, in flow</span><h1>Everything you need<br /><span>for your PDFs.</span></h1><p>Convert, organize, and compress your documents in seconds.</p><div className="hero-actions"><a className="button button-primary button-large" href="#tools">Explore PDF Tools <ArrowRight size={17} /></a><a className="button button-secondary button-large" href="#how">How it works <ChevronDown size={16} /></a></div><div className="hero-proof"><div className="avatar-stack"><span>J</span><span>M</span><span>A</span><span>+</span></div><span>Trusted by teams who value their time</span></div></div></section><ToolGrid /><section id="features" className="section trust-section"><div className="container"><div className="center-heading"><span className="eyebrow">Built around your workflow</span><h2>Simple. Secure. Built for<br />everyday documents.</h2></div><div className="feature-grid">{[[ShieldCheck,'Private by design','Your files are yours. We keep your workflow focused and your documents protected.'],[Zap,'Fast processing','No unnecessary steps. Get from upload to finished document in a few clicks.'],[Sparkles,'Easy to use','A clear, thoughtful experience that feels natural from the very first file.']].map(([Icon,title,text]) => <div className="feature-card" key={title as string}><div className="feature-icon"><Icon size={22} /></div><h3>{title as string}</h3><p>{text as string}</p></div>)}</div></div></section><section id="how" className="section how-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">A better way to work</span><h2>Three steps. Zero guesswork.</h2></div></div><div className="steps">{[['01','Choose a tool','Start with the document task you need to complete.'],['02','Upload your file','Drag and drop your file or select it from your device.'],['03','Download the result','Your finished document is ready to use and share.']].map(([number,title,text]) => <div className="step" key={number}><span className="step-number">{number}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section><section id="pricing" className="cta-section"><div className="container cta-inner"><div><span className="eyebrow eyebrow-light">Make room for better work</span><h2>Ready to simplify your<br />PDF workflow?</h2></div><a className="button button-light button-large" href="#tools">Start using DocFlow <ArrowRight size={17} /></a></div></section></main><Footer /></> }

const configs: Record<ToolKey,{title:string; description:string; accept:string; action:string; result:string; multiple?:boolean}> = { 'pdf-to-word':{title:'PDF to Word',description:'Convert your PDF files into editable Word documents.',accept:'PDF',action:'Convert to Word',result:'DOCX'},'word-to-pdf':{title:'Word to PDF',description:'Turn your Word documents into polished PDF files.',accept:'DOC or DOCX',action:'Convert to PDF',result:'PDF'},'jpg-to-pdf':{title:'JPG to PDF',description:'Convert images into a single professional PDF.',accept:'JPG or PNG',action:'Create PDF',result:'PDF',multiple:true},'pdf-to-jpg':{title:'PDF to JPG',description:'Convert PDF pages into high-quality JPG images.',accept:'PDF',action:'Convert to JPG',result:'JPG'},'merge-pdf':{title:'Merge PDF',description:'Combine multiple PDF files into one document.',accept:'PDF',action:'Merge PDFs',result:'PDF',multiple:true},'split-pdf':{title:'Split PDF',description:'Extract pages or divide a PDF into separate files.',accept:'PDF',action:'Split PDF',result:'PDF'},'compress-pdf':{title:'Compress PDF',description:'Reduce PDF file size while keeping great quality.',accept:'PDF',action:'Compress PDF',result:'PDF'} }

function FileList({ files, remove, reorder }: { files: File[]; remove:(i:number)=>void; reorder:(from:number,to:number)=>void }) { return <div className="file-list">{files.map((file,i) => <div className="file-row" draggable onDragStart={e => e.dataTransfer.setData('text/plain',String(i))} onDragOver={e => e.preventDefault()} onDrop={e => reorder(Number(e.dataTransfer.getData('text/plain')),i)} key={`${file.name}-${i}`}><GripVertical className="grip" size={17}/><div className="file-badge"><FileText size={18}/></div><div className="file-meta"><strong>{file.name}</strong><span>{(file.size/1024/1024).toFixed(2)} MB</span></div><button className="icon-button" aria-label={`Remove ${file.name}`} onClick={() => remove(i)}><X size={17}/></button></div>)}</div> }
function UploadZone({ select, multiple, accept }: {select:(files:File[])=>void; multiple?:boolean; accept:string}) { return <label className="upload-zone" onDragOver={e => {e.preventDefault(); e.currentTarget.classList.add('is-dragging')}} onDragLeave={e => e.currentTarget.classList.remove('is-dragging')} onDrop={e => {e.preventDefault(); e.currentTarget.classList.remove('is-dragging'); select(Array.from(e.dataTransfer.files))}}><input type="file" accept={accept} multiple={multiple} onChange={e => select(Array.from(e.target.files || []))}/><div className="upload-icon"><Upload size={22}/></div><h3>Drag & drop your {accept} here</h3><p>or choose a file from your device</p><span className="button button-primary">Select {multiple ? 'files' : 'a file'}</span><small>Maximum file size: 50 MB</small></label> }
function StateMessage({ type, config, reset }: {type:'processing'|'success'|'error'; config:typeof configs[ToolKey]; reset:()=>void}) { if(type==='processing') return <div className="state-card"><div className="loader"><span /></div><h2>Processing your file...</h2><div className="progress"><span /></div><strong>82%</strong><p>Please wait while we prepare your document.</p></div>; if(type==='error') return <div className="state-card"><div className="state-icon error"><X size={25}/></div><h2>Something went wrong</h2><p>Please try again or choose another file.</p><button className="button button-primary" onClick={reset}>Try again</button></div>; return <div className="state-card"><div className="state-icon"><Check size={25}/></div><h2>Your file is ready!</h2><p>document.{config.result.toLowerCase()}</p><div className="state-actions"><button className="button button-primary">Download {config.result}</button><button className="button button-secondary" onClick={reset}>Convert another file</button></div></div> }
export function ToolPage({ toolKey }: {toolKey:ToolKey}) { const config=configs[toolKey]; const [files,setFiles]=useState<File[]>([]); const [state,setState]=useState<'idle'|'processing'|'success'|'error'>('idle'); const select=(newFiles:File[])=>setFiles(config.multiple ? newFiles : newFiles.slice(0,1)); const reset=()=>{setFiles([]);setState('idle')}; const reorder=(from:number,to:number)=>{const next=[...files]; const [item]=next.splice(from,1); next.splice(to,0,item);setFiles(next)}; return <><Navbar/><main className="tool-page"><div className="container tool-page-inner"><Link href="/" className="back-link">← All PDF tools</Link><div className="tool-header"><div className="tool-page-icon"><FileText size={25}/></div><span className="eyebrow">DocFlow tool</span><h1>{config.title}</h1><p>{config.description}</p></div><div className="workspace">{state !== 'idle' ? <StateMessage type={state} config={config} reset={reset}/> : files.length===0 ? <UploadZone select={select} multiple={config.multiple} accept={config.accept}/> : <div className="uploaded-state"><div className="workspace-top"><div><span className="eyebrow">Ready to process</span><h2>Your {config.multiple ? 'files are' : 'file is'} ready.</h2></div><button className="button button-ghost" onClick={reset}>Clear all</button></div><FileList files={files} remove={i=>setFiles(files.filter((_,idx)=>idx!==i))} reorder={reorder}/>{toolKey==='compress-pdf' && <div className="option-grid"><button className="option-card"><strong>Extreme</strong><span>Smallest file</span></button><button className="option-card selected"><strong>Recommended</strong><span>Great balance</span></button><button className="option-card"><strong>Less compression</strong><span>Best quality</span></button></div>}{toolKey==='pdf-to-jpg' && <div className="quality-row"><strong>Image quality</strong><button className="quality active">High</button><button className="quality">Medium</button><button className="quality">Low</button></div>}<button className="button button-primary button-large process-button" onClick={() => {setState('processing');setTimeout(()=>setState('success'),1400)}}>{config.action} <ArrowRight size={17}/></button></div>}</div><p className="security-note"><ShieldCheck size={16}/> Files are processed securely and never shared.</p></div></main><Footer/></> }
